apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-2tjl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-2tjl@sha256:e0031ffb0e959fb8cb9743e13c87c521c767aeee50368cae5e839147c92324ae
        name: my-nodejs
        resources: {}
status: {}
